"""
Code generation templates for QuickApp
Contains templates for FastAPI + Jinja2 + SQLite applications
"""

from typing import Dict, Any


def get_main_py_template() -> str:
    """Template for main.py FastAPI application"""
    return '''"""
{{app_description}}
Generated by QuickApp
"""

from contextlib import asynccontextmanager
from fastapi import FastAPI, Request, Depends, Form, HTTPException
from fastapi.responses import HTMLResponse, RedirectResponse
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates
from sqlalchemy.orm import Session
from typing import Optional

from database import get_db, init_db
import models

@asynccontextmanager
async def lifespan(app: FastAPI):
    """Lifecycle events for the FastAPI application"""
    # Initialize database
    init_db()
    yield
    # Cleanup logic (if any) could go here

app = FastAPI(title="{{app_name}}", lifespan=lifespan)

# Mount static files and templates
app.mount("/static", StaticFiles(directory="static"), name="static")
templates = Jinja2Templates(directory="templates")


{{root_route}}


{{additional_routes}}


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
'''


def get_models_py_template() -> str:
    """Template for models.py database models"""
    return '''"""
Database models
"""

from sqlalchemy import Column, Integer, String, Boolean, DateTime, Text
from sqlalchemy.sql import func
from database import Base


{{model_definitions}}
'''


def get_database_py_template() -> str:
    """Template for database.py configuration"""
    return '''"""
Database configuration with SQLite and WAL mode
"""

from sqlalchemy import create_engine, event
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

# SQLite database with WAL mode for better concurrency
SQLALCHEMY_DATABASE_URL = "sqlite:///./app.db"

# Enable WAL mode and other optimizations
engine = create_engine(
    SQLALCHEMY_DATABASE_URL,
    connect_args={
        "check_same_thread": False,
    }
)


# Enable WAL mode for SQLite
@event.listens_for(engine, "connect")
def set_sqlite_pragma(dbapi_conn, connection_record):
    cursor = dbapi_conn.cursor()
    cursor.execute("PRAGMA journal_mode=WAL")
    cursor.execute("PRAGMA synchronous=NORMAL")
    cursor.execute("PRAGMA cache_size=-64000")  # 64MB cache
    cursor.execute("PRAGMA temp_store=MEMORY")
    cursor.execute("PRAGMA mmap_size=268435456")  # 256MB mmap
    cursor.close()


SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()


def get_db():
    """Database session dependency"""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


def init_db():
    """Initialize database tables"""
    Base.metadata.create_all(bind=engine)
'''


def get_base_html_template() -> str:
    """Template for base.html Jinja2 template with Tailwind v4"""
    return '''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{{ app_name }}{% endblock %}</title>
    <!-- Tailwind CSS v4 Play CDN -->
    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
    <link rel="stylesheet" href="{{ url_for('static', path='/style.css') }}">
    <style type="text/tailwindcss">
        @theme {
            --color-primary: var(--color-indigo-600);
            --color-secondary: var(--color-indigo-500);
        }
    </style>
</head>
<body class="bg-slate-50 text-slate-900 min-h-screen">
    <div class="max-w-4xl mx-auto px-4 py-8">
        <header class="text-center mb-12">
            <h1 class="text-4xl font-bold text-indigo-600 tracking-tight">{{ app_name }}</h1>
        </header>
        
        <main class="bg-white rounded-xl shadow-sm border border-slate-200 min-h-[400px] p-6 md:p-8">
            {% block content %}{% endblock %}
        </main>
        
        <footer class="text-center mt-12 py-6 border-t border-slate-200 text-slate-500 text-sm">
            <p>Generated by QuickApp &bull; Built with FastAPI & Tailwind v4</p>
        </footer>
    </div>
    
    {% block scripts %}{% endblock %}
</body>
</html>
'''


def get_index_html_template() -> str:
    """Template for index.html"""
    return '''{% extends "base.html" %}

{% block content %}
{{content}}
{% endblock %}
'''


def get_style_css_template() -> str:
    """Template for style.css with Tailwind v4 directives"""
    return '''/* Tailwind v4 CSS-first configuration */

@theme {
  /* Add custom design tokens here if needed */
  --font-sans: "Inter", ui-sans-serif, system-ui, sans-serif;
}

/* Custom styles that can't be handled by utilities */
.glass {
  background: rgba(255, 255, 255, 0.7);
  backdrop-filter: blur(10px);
  border: 1px solid rgba(255, 255, 255, 0.2);
}
'''


def get_pyproject_toml_template() -> str:
    """Template for pyproject.toml (uv)"""
    return '''[project]
name = "{{app_name_slug}}"
version = "0.1.0"
description = "{{app_description}}"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.115.0",
    "uvicorn[standard]>=0.30.0",
    "jinja2>=3.1.0",
    "sqlalchemy>=2.0.0",
    "python-multipart>=0.0.9",
    "pytailwindcss>=0.2.0",
]

[tool.uv]
managed = true
'''


# Template data structure
TEMPLATES: Dict[str, Any] = {
    "main.py": get_main_py_template,
    "models.py": get_models_py_template,
    "database.py": get_database_py_template,
    "templates/base.html": get_base_html_template,
    "templates/index.html": get_index_html_template,
    "static/style.css": get_style_css_template,
    "pyproject.toml": get_pyproject_toml_template,
}
